server:
  port: 8081

spring:
  zipkin:
    # base-url: http://localhost:9411/
    sender:   # 指定当前应用要将Sleuth生成的日志发送给Kafka
      type: kafka

  kafka:     # 指定Kafka集群
    bootstrap-servers: kafkaOS1:9092,kafkaOS2:9092,kafkaOS3:9092

  sleuth:
    sampler:
      probability: 1.0

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 111

  application:
    name: abcmsc-provider-depart   # 暴露微服务名称

# 指定Eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

info:
  company.name: www.abc.com
  company.addr: China Beijing
  company.tel: 12345678
  app.name: abc-msc
  app.desc: mic-server-cloud
  author: abc