spring:
  application:  # 指定微服务对外暴露的名称
    name: abcmsc-consumer-depart

  # 连接Redis服务器
  redis:
    host: redis5OS
    port: 6379
    password: 111

eureka:
  client:
    service-url: # 指定Eureka服务注册中心
      defaultZone: http://localhost:8000/eureka


feign:
  client:
    config:
      default:
        connectTimeout: 5000  # 指定Feign连接提供者的超时时限
        readTimeout: 5000    # 指定Feign从请求到获取提供者响应的超时时限