spring:
  application:
    name: abcmsc-consumer-depart

  zipkin:
    # base-url: http://localhost:9411/
    sender:
      type: kafka

  kafka:
    bootstrap-servers: kafkaOS1:9092,kafkaOS2:9092,kafkaOS3:9092

  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka


