server:
  port: 8082

spring:
  zipkin:  # 指定zipkin服务端地址
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 0.8   # 指定采样率为80%，默认为0.1，即10%

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 111

  application:
    name: abcmsc-provider-depart

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

info:
  company.name: www.abc.com
  company.addr: China Beijing
  company.tel: 12345678
  app.name: abc-msc
  app.desc: mic-server-cloud
  author: abc